# Generated by Django 6.0.6 on 2026-08-11 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('cinema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking_per_session_seat',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELED'), _negated=True), fields=('session', 'seat'), name='unique_active_booking_per_session_seat'),
        ),
    ]
